stages:
  - build
  - deploy

build:
  stage: build
  only:
    - staging
  tags:
    - development
  script:
    - if [ "$(docker ps -a | grep icademy-app)" ]; then 
        echo "Container Exists";
        docker rm -f icademy-app;
        docker rmi -f icademy/app:latest;
      else
        echo "Container Not Found";
      fi
    - cd /home/ubuntu/ideku-react && sudo git pull origin staging
    - sudo cp /docker/icademy-app/api.js /home/ubuntu/ideku-react/src/repository
    - cd /home/ubuntu/ideku-react && sudo npm install
    - cd /home/ubuntu/ideku-react && sudo npm run build
    - cd /home/ubuntu/ideku-react && docker build -t icademy/app:latest .

deploy:
  stage: deploy
  only:
    - staging
  tags:
    - development
  environment:
    name: "Dev Icademy App"
    url: https://app.icademy.dev.kelola.co.id
  script:
    - if [ "$(docker ps -a | grep icademy-app)" ]; then 
        echo "Container Exists";
        docker rm -f icademy-app;
      else
        echo "Container Not Found";
      fi
    - cd /home/ubuntu/ideku-react && docker run --name icademy-app --restart=always -dit -p 3000:80 icademy/app:latest

