stages:
  - build
  - deploy

build:
  stage: build
  only:
    - staging
  tags:
    - development
  script:
    - docker rm -f icademy-app
    - docker rmi -f icademy/app:latest
    - cd /home/ubuntu/ideku-react && sudo git pull origin staging
    - sudo cp /docker/icademy-app/api.js /home/ubuntu/ideku-react/src/repository
    - cd /home/ubuntu/ideku-react && docker build -t icademy/app:latest .

deploy:
  stage: deploy
  only:
    - staging
  tags:
    - development
  script:
    - cd /home/ubuntu/ideku-react && docker run --name icademy-app -dit -p 3000:80 icademy/app:latest

